import { expect } from '@playwright/test'
import { expectNoA11yViolations, expectNoHorizontalScroll, snap, test } from './helpers.ts'

test('личные разделы, профиль, подписи и Последний бой', async ({ page }, testInfo) => {
  // Длинный сквозной сценарий: вход, профиль, разделы, «Последний бой», проверка истории, выход
  test.slow()
  await page.goto('/other')
  for (const section of ['ar', 'archive', 'photo'])
    await expect(page.getByTestId(`other-${section}`)).toHaveCount(0)
  await expect(page.getByTestId('other-last-battle')).toBeVisible()
  await expectNoA11yViolations(page)
  await snap(page, testInfo, 'account-01-guest')
  await page.goto('/other?section=ar')
  await expect(page.getByTestId('signin-form')).toBeVisible()
  await page.getByTestId('signin-login').fill('anna@example.com')
  await page.getByTestId('signin-password').fill('example-password')
  await page.getByTestId('signin-submit').click()
  await page.getByTestId('profile-name-input').fill('Анна Иванова')
  await page.getByTestId('profile-city').fill('Орёл')
  await page.getByTestId('profile-bio').fill('Изучаю историю своей семьи и Орловского края.')
  await page.getByTestId('profile-save').click()
  await expect(page.getByTestId('profile-saved')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('profile-name')).toHaveText('Анна Иванова')
  await page.getByTestId('profile').scrollIntoViewIfNeeded()
  await expectNoHorizontalScroll(page)
  await expectNoA11yViolations(page)
  await snap(page, testInfo, 'account-02-profile')
  // «Другое»: список разделов на /other, у каждого раздела своя страница с «Назад»
  await page.getByTestId('other-back').click()
  await expect(page).toHaveURL(/\/other$/)
  for (const section of ['account', 'archive', 'ar', 'photo'])
    await expect(page.getByTestId(`other-${section}`)).toBeVisible()
  await page.getByTestId('other-photo').click()
  await expect(page.getByTestId('screen-other-photo')).toBeVisible()
  await page.getByTestId('other-back').click()
  await expect(page.getByTestId('other-account')).toBeVisible()
  await page.getByTestId('other-last-battle').click()
  await expect(page.getByTestId('last-battle-site-S01')).toBeVisible()
  await expectNoA11yViolations(page)
  await snap(page, testInfo, 'account-03-last-battle')
  await page.getByTestId('last-battle-filter').selectOption('archive_confirmed')
  await expect(page.getByTestId('last-battle-site-S01')).toHaveCount(0)
  await page.getByTestId('last-battle-site-S02').click()
  await expect(page).toHaveURL(/\/last-battle\/S02$/)
  await page.goto('/roles')
  await page.getByTestId('role-verifier').click()
  await page.goto('/archive/ST03')
  await expect(page.getByTestId('review-author')).toHaveValue('Анна Иванова')
  await page.getByTestId('review-note').fill('Нужен номер полевой почты')
  await page.getByTestId('review-clarify').click()
  await expect(page.getByTestId('story-review-note')).toContainText('Анна Иванова')
  await page.getByTestId('nav-role').click()
  await page.getByTestId('profile-signout').click()
  for (const section of ['ar', 'archive', 'photo'])
    await expect(page.getByTestId(`other-${section}`)).toHaveCount(0)
  await page.goto('/live')
  await expect(page.getByTestId('signin-form')).toBeVisible()
  await expect(page.getByTestId('screen-live-photos')).toHaveCount(0)
  await page.goto('/archive')
  await expect(page.getByTestId('archive-new')).toHaveCount(0)
  await expect(page.getByTestId('archive-prompt')).toHaveCount(0)
  await expect(page.getByTestId('site-footer').getByText('Есть история?')).toHaveCount(0)
})
